#!/usr/bin/env bash
#
# Build the Kadi release APK (debug-signed, JS bundled — runs standalone, no
# Metro). Output: android/app/build/outputs/apk/release/app-release.apk, plus a
# version-named copy at the repo root for manual sharing.
#
# Env overrides: JAVA_HOME, ANDROID_HOME
#
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
export JAVA_HOME="${JAVA_HOME:-/usr/lib/jvm/java-21-openjdk-amd64}"
export ANDROID_HOME="${ANDROID_HOME:-$HOME/Android/Sdk}"
APK="$ROOT_DIR/android/app/build/outputs/apk/release/app-release.apk"

# Keep the bundled version constants in lockstep with app.json so the launch-time
# update check compares against the real shipping version (see src/appVersion.ts).
VCODE="$(node -p "require('$ROOT_DIR/app.json').expo.android.versionCode")"
VNAME="$(node -p "require('$ROOT_DIR/app.json').expo.version")"
cat > "$ROOT_DIR/src/appVersion.ts" <<EOF
// The running build's version, mirrored from app.json. Regenerated by
// scripts/build-apk.sh at release-build time so it can never drift from the APK
// it ships in. The update check (src/api/appUpdate.ts) compares BUILD_VERSION_CODE
// against the server manifest to decide whether a newer build is available.
export const BUILD_VERSION_CODE = ${VCODE};
export const BUILD_VERSION_NAME = '${VNAME}';
EOF
echo "→ Synced src/appVersion.ts to v${VNAME}/${VCODE}"

echo "→ Building Kadi release APK (JAVA_HOME=$JAVA_HOME)…"
( cd "$ROOT_DIR/android" && ./gradlew assembleRelease )

[[ -f "$APK" ]] || { echo "✗ Build finished but APK not found at $APK"; exit 1; }

VERSION="$(node -p "require('$ROOT_DIR/app.json').expo.version" 2>/dev/null || echo dev)"
rm -f "$ROOT_DIR"/Kadi-v*.apk
cp "$APK" "$ROOT_DIR/Kadi-v${VERSION}.apk"
echo "✓ Built Kadi-v${VERSION}.apk ($(du -h "$APK" | cut -f1))"
