// The running build's version, mirrored from app.json. Regenerated by
// scripts/build-apk.sh at release-build time so it can never drift from the APK
// it ships in. The update check (src/api/appUpdate.ts) compares BUILD_VERSION_CODE
// against the server manifest to decide whether a newer build is available.
export const BUILD_VERSION_CODE = 23;
export const BUILD_VERSION_NAME = '1.7.4';
